-- ============================================================
-- SpeedBet V2 — AI Crash Engine (Addendum v2.1)
-- ============================================================

-- AI-generated crash schedule
CREATE TABLE game_crash_schedule (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_slug           VARCHAR(20) NOT NULL,
    round_number        BIGINT NOT NULL,
    crash_at            NUMERIC(8,2) NOT NULL,
    tier                VARCHAR(10) NOT NULL,
    is_high_crash       BOOLEAN NOT NULL DEFAULT FALSE,
    is_extreme_crash    BOOLEAN NOT NULL DEFAULT FALSE,
    generated_by        VARCHAR(20) NOT NULL DEFAULT 'AI',
    generated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    played_at           TIMESTAMPTZ,
    admin_notified      BOOLEAN NOT NULL DEFAULT FALSE,
    override_reason     TEXT,
    UNIQUE(game_slug, round_number)
);

-- Alert cards generated by admins
CREATE TABLE crash_alert_cards (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    crash_schedule_id     UUID REFERENCES game_crash_schedule(id),
    generated_by_admin_id UUID REFERENCES users(id),
    game_slug             VARCHAR(20) NOT NULL,
    crash_at              NUMERIC(8,2) NOT NULL,
    suggested_cashout_min NUMERIC(8,2),
    suggested_cashout_max NUMERIC(8,2),
    custom_message        TEXT,
    image_path            TEXT NOT NULL,
    generated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    view_count            INT NOT NULL DEFAULT 0
);

-- User crash alert subscriptions
CREATE TABLE crash_alert_subscriptions (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id      UUID REFERENCES users(id),
    game_slug    VARCHAR(20) NOT NULL,
    notify_above NUMERIC(8,2) NOT NULL DEFAULT 10.0,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, game_slug)
);

-- Crash AI insights (generated hourly per game)
CREATE TABLE crash_insights (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_slug             VARCHAR(20) NOT NULL,
    insight_text          TEXT NOT NULL,
    suggested_cashout_min NUMERIC(8,2),
    suggested_cashout_max NUMERIC(8,2),
    generated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- INDEXES
CREATE INDEX idx_crash_schedule_unplayed ON game_crash_schedule(game_slug, played_at)
    WHERE played_at IS NULL;
CREATE INDEX idx_crash_schedule_high ON game_crash_schedule(is_high_crash)
    WHERE is_high_crash = TRUE;
CREATE INDEX idx_crash_schedule_game_round ON game_crash_schedule(game_slug, round_number);
CREATE INDEX idx_crash_alert_cards_game ON crash_alert_cards(game_slug);
CREATE INDEX idx_crash_insights_game ON crash_insights(game_slug, generated_at DESC);
